version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17  # Node.js official CircleCI image
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  build_and_test:
    jobs:
      - build
